import React, { useMemo, useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { Mail, ShieldCheck, Sparkles, UserRound, MapPin } from 'lucide-react';
import './CompleteProfilePage.css';

const parseResponseSafely = async (response) => {
    const raw = await response.text();
    if (!raw) return null;

    try {
        return JSON.parse(raw);
    } catch {
        return null;
    }
};

const CompleteProfilePage = () => {
    const navigate = useNavigate();
    const { user, getToken, getDeviceId, updateUser } = useAuth();
    const [name, setName] = useState(String(user?.name || '').trim());
    const [email, setEmail] = useState(String(user?.email || '').trim().toLowerCase());
    const [error, setError] = useState('');
    const [submitting, setSubmitting] = useState(false);
    const [saved, setSaved] = useState(false);     // brief "✓ Saved" confirmation
    const [leaving, setLeaving] = useState(false);  // card fade-out on success
    const [isEmailAutoGenerated, setIsEmailAutoGenerated] = useState(!email || email.endsWith('@ltdic.com'));
    const [locations, setLocations] = useState([]);
    const [locationId, setLocationId] = useState(String(user?.location_id || ''));

    // Load site list for the location dropdown (allowlisted for incomplete profiles).
    useEffect(() => {
        (async () => {
            try {
                const token = getToken();
                if (!token) return;
                const res = await fetch('/api/locations', {
                    headers: { Authorization: `Bearer ${token}`, 'X-Device-ID': getDeviceId() },
                });
                if (res.ok) setLocations(await res.json());
            } catch (e) {
                console.warn('location load failed', e);
            }
        })();
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    // On mount, if we have a real name but a fallback email, auto-fix it immediately
    React.useEffect(() => {
        const currentEmail = String(user?.email || '').trim().toLowerCase();
        if ((!currentEmail || currentEmail.endsWith('@ltdic.com')) && name) {
            const parts = name.trim().toLowerCase().split(/\s+/);
            if (parts.length >= 2) {
                setEmail(`${parts[0]}.${parts[parts.length - 1]}@larsentoubro.com`);
                setIsEmailAutoGenerated(true);
            }
        }
    }, [user?.email]);

    const handleNameChange = (event) => {
        const newName = event.target.value;
        setName(newName);
        
        if (isEmailAutoGenerated) {
            const parts = newName.trim().toLowerCase().split(/\s+/);
            if (parts.length >= 2) {
                setEmail(`${parts[0]}.${parts[parts.length - 1]}@larsentoubro.com`);
            } else if (parts.length === 1 && parts[0]) {
                setEmail(`${parts[0]}@larsentoubro.com`);
            } else {
                setEmail('');
            }
        }
    };

    const handleEmailChange = (event) => {
        setEmail(event.target.value);
        setIsEmailAutoGenerated(false);
    };

    const canSubmit = useMemo(() => {

        return name.trim().length > 0 && email.trim().length > 0 && String(locationId).length > 0;
    }, [name, email, locationId]);

    const handleSubmit = async (event) => {
        event.preventDefault();
        if (!canSubmit || submitting) {
            return;
        }

        setSubmitting(true);
        setError('');

        try {
            const token = getToken();
            if (!token) {
                navigate('/login', { replace: true });
                return;
            }

            const response = await fetch('/api/users/complete-profile', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`,
                    'X-Device-ID': getDeviceId(),
                },
                body: JSON.stringify({
                    name: name.trim(),
                    email: email.trim().toLowerCase(),
                    location_id: locationId || null,
                }),
            });

            const data = await parseResponseSafely(response);

            if (!response.ok) {
                throw new Error(data?.error || 'Unable to save profile.');
            }

            const updated = data?.user;
            if (!updated) {
                throw new Error('Invalid profile response from server.');
            }

            updateUser({
                ...user,
                ...updated,
                profile_completed: Number(updated.profile_completed || 0),
            });
            // Success choreography: spinner → ✓ Saved → card fades out → navigate.
            setSubmitting(false);
            setSaved(true);
            setTimeout(() => setLeaving(true), 450);
            setTimeout(() => navigate('/hub', { replace: true }), 700);
        } catch (submitError) {
            setError(submitError.message || 'Unable to save profile.');
            setSubmitting(false);
        }
    };

    return (
        <div className="complete-profile-shell">
            <div className="complete-profile-aurora complete-profile-aurora-one" aria-hidden="true"></div>
            <div className="complete-profile-aurora complete-profile-aurora-two" aria-hidden="true"></div>
            <div className="complete-profile-grid" aria-hidden="true"></div>

            <div className={`complete-profile-layout${leaving ? ' is-leaving' : ''}`}>
                <section className="complete-profile-brand-panel">
                    <p className="complete-profile-pill">
                        <Sparkles size={14} />
                        First Login Setup
                    </p>

                    <h1>Welcome to InFloAI</h1>
                    <p>
                        Set your profile once and continue with secure PS Number based access.
                    </p>

                    <div className="complete-profile-info-list">
                        <div className="complete-profile-info-item">
                            <ShieldCheck size={18} />
                            <span>Authentication is managed by your domain (LDAP).</span>
                        </div>

                        {user?.ps_number && (
                            <div className="complete-profile-info-item">
                                <UserRound size={18} />
                                <span>
                                    Your PS Number: <strong>{user.ps_number}</strong>
                                </span>
                            </div>
                        )}
                    </div>
                </section>

                <section className="complete-profile-form-panel">
                    <h2>Complete Your Profile</h2>
                    <p className="complete-profile-form-subtitle">Please confirm your name and email to continue.</p>

                    {error && <div className="complete-profile-error">{error}</div>}

                    <form className="complete-profile-form" onSubmit={handleSubmit}>
                        <label htmlFor="complete-name">Full Name</label>
                        <div className="complete-profile-input-wrap">
                            <UserRound size={18} className="complete-profile-input-icon" />
                            <input
                                id="complete-name"
                                type="text"
                                value={name}
                                onChange={handleNameChange}
                                placeholder="Enter your full name"
                                required
                            />
                        </div>

                        <label htmlFor="complete-email">Email Address</label>
                        <div className="complete-profile-input-wrap">
                            <Mail size={18} className="complete-profile-input-icon" />
                            <input
                                id="complete-email"
                                type="email"
                                value={email}
                                onChange={handleEmailChange}
                                placeholder="name@company.com"
                                required
                            />
                        </div>

                        <label htmlFor="complete-location">Location / Site</label>
                        <div className="complete-profile-input-wrap">
                            <MapPin size={18} className="complete-profile-input-icon" />
                            <select
                                id="complete-location"
                                value={locationId}
                                onChange={(e) => setLocationId(e.target.value)}
                                required
                            >
                                <option value="">Select your location…</option>
                                {locations.map((l) => (
                                    <option key={l.id} value={l.id}>{l.name}</option>
                                ))}
                            </select>
                        </div>

                        <button type="submit" disabled={!canSubmit || submitting || saved} className={`complete-profile-submit${saved ? ' is-saved' : ''}`}>
                            {saved ? (
                                <span className="cp-btn-inline">✓ Saved</span>
                            ) : submitting ? (
                                <span className="cp-btn-inline"><span className="cp-spinner" /> Saving…</span>
                            ) : (
                                'Save and Continue'
                            )}
                        </button>
                    </form>
                </section>
            </div>
        </div>
    );
};

export default CompleteProfilePage;
