import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { convert } from '@opendataloader/pdf';

/**
 * Normalizes text by collapsing whitespace
 */
const normalizeText = (text) => (text || '').replace(/\s+/g, ' ').trim();

/**
 * Extracts core fields from markdown generated by opendataloader-pdf
 */
const extractFieldsFromMarkdown = (markdown) => {
    const lines = markdown.split('\n').map(line => line.trim()).filter(Boolean);
    const normalizedMarkdown = normalizeText(markdown);
    
    let vendorName = '';
    let invoiceNumber = '';
    let amount = '';
    let date = '';
    let poNumber = '';

    const supplierMatch = markdown.match(/(?:SUPPLIER|VENDOR)\s+NAME\s*[:|]+\s*([^|\n]+)/i);
    if (supplierMatch && supplierMatch[1].trim() !== '-') {
        vendorName = supplierMatch[1].trim();
    } else {
        // Look for typical vendor line at the top (allow headings and bold text)
        const validVendorLines = lines.filter(l => {
            const clean = l.replace(/^#+\s*/, '').replace(/\*\*/g, '').trim();
            return !l.startsWith('|') && !l.startsWith('![') && clean.length > 4 && !/^(?:TAX\s*|PROFORMA\s*)?INVOICE$/i.test(clean);
        });
        
        if (validVendorLines.length > 0 && !vendorName) {
            vendorName = validVendorLines[0].replace(/^#+\s*/, '').replace(/\*\*/g, '').trim();
        }
    }

    // Special fallback for Hornbill: Their name is trapped inside an image logo, so OpenDataLoader misses it.
    // We can confidently identify them by their GSTIN or their HBS/ invoice number prefix.
    if (/AAECH5664G1ZG|HBS\//i.test(markdown)) {
        vendorName = 'Hornbill Studios Private Limited';
    }

    // 2. Invoice Number
    // Pattern B first (more specific): 'Invoice No & Date : SHO/26-27/00566 29-May-26' (Tally/ERP format)
    const invMatchB = markdown.match(/Invoice\s*No\s*(?:[&]\s*Date\s*)?[:\-]?\s*([A-Z0-9][A-Z0-9\-\/]+)/i);
    // Pattern A fallback: Standard 'Invoice No : XYZ' or 'Invoice Number XYZ'
    const invMatchA = markdown.match(/(?:INVOICE|INV|BILL)\s*(?:NO\.?|NUMBER|#|NUM)\s*[:\-|]?\s*([A-Z0-9][A-Z0-9\-\/]+)/i);
    const invMatch = invMatchB || invMatchA;
    if (invMatch) {
        let extractedInv = invMatch[1].trim();
        // Ignore matches that accidentally grab the next field's label or Eway Bill number
        if (!/^(EWAY|DATE|BILL|INV|NO)$/i.test(extractedInv)) {
            invoiceNumber = extractedInv;
        }
    }

    // 3. Amount - handled in section 3b below (gross with tax)
    // (amount variable already declared above)

    // 4. Date
    // Pattern A: Standard labeled date 'INVOICE DATE : YYYY-MM-DD' or 'DATE : DD/MM/YYYY'
    const dateMatchA = markdown.match(/(?:INVOICE DATE|CLAIMED DATE|DATE)\s*[:\-|]+\s*(\d{4}[-/.]\d{1,2}[-/.]\d{1,2}|\d{1,2}[-/.]\d{1,2}[-/.]\d{2,4})/i);
    // Pattern B: 'Invoice No & Date : SHO/26-27/00566 29-May-26' — date follows invoice number
    const dateMatchB = markdown.match(/Invoice\s*No\s*[&]\s*Date\s*:\s*\S+\s+(\d{1,2}[-\/][A-Za-z]{3}[-\/\s]\d{2,4})/i);
    // Pattern C: Ack Date from IRN block (fallback)
    const dateMatchC = !dateMatchA && !dateMatchB ? markdown.match(/Ack\s*Date\s*[:\-]?\s*(\d{4}-\d{2}-\d{2})/i) : null;
    const rawDateStr = (dateMatchA || dateMatchB || dateMatchC)?.[1]?.trim() || '';
    if (rawDateStr) {
        // Handle 'DD-Mon-YY' or 'DD-Mon-YYYY' format e.g. '29-May-26'
        const monthNames = { jan:1, feb:2, mar:3, apr:4, may:5, jun:6, jul:7, aug:8, sep:9, oct:10, nov:11, dec:12 };
        const namedMonth = rawDateStr.match(/^(\d{1,2})[-\/]([A-Za-z]{3})[-\/\s](\d{2,4})$/);
        if (namedMonth) {
            let year = Number.parseInt(namedMonth[3], 10);
            if (year < 100) year += 2000;
            const month = String(monthNames[namedMonth[2].toLowerCase().slice(0,3)] || 1).padStart(2, '0');
            const day = String(namedMonth[1]).padStart(2, '0');
            date = `${year}-${month}-${day}`;
        } else {
            const dmy = rawDateStr.match(/^(\d{1,2})[-\/.](\d{1,2})[-\/.](\d{2,4})$/);
            if (dmy) {
                let year = Number.parseInt(dmy[3], 10);
                if (year < 100) year += 2000;
                const month = dmy[2].padStart(2, '0');
                const day = dmy[1].padStart(2, '0');
                date = `${year}-${month}-${day}`;
            } else {
                // Probably YYYY-MM-DD already
                date = rawDateStr.replace(/\./g, '-');
            }
        }
    }

    // 5. PO Number
    const poMatch = markdown.match(/(?:buy(?:er'?s)?\s*order\s*no\.?|purchase\s*order\s*no\.?|po\s*no\.?|p\.o\.\s*no\.?)\s*[:\-|]+\s*([A-Z0-9][A-Z0-9\s\/-]{2,40})/i);
    if (poMatch) {
        poNumber = poMatch[1].split(/[\s,;|]+/)[0].trim();
    }

    // 6. Line Items (Table parsing)
    let lineItems = [];
    let inTable = false;
    let descIdx = -1;
    let amtIdx = -1;
    let qtyIdx = -1;
    let rateIdx = -1;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i];
        if (line.startsWith('|') && lines[i + 1] && lines[i + 1].includes('|---')) {
            const headers = line.split('|').map(h => h.trim().toLowerCase());
            descIdx = headers.findIndex(h => h.includes('description') || h.includes('particulars') || h.includes('item') || h.includes('goods') || h.includes('service'));
            amtIdx = headers.findIndex(h => h.includes('amount') || h.includes('total') || h.includes('value'));
            qtyIdx = headers.findIndex(h => h.includes('qty') || h.includes('quantity') || h.includes('nos') || h.includes('unit') && !h.includes('unitprice'));
            rateIdx = headers.findIndex(h => h.includes('rate') || h.includes('price') || h.includes('unit price') || h.includes('unit cost'));
            inTable = true;
            i++; // skip the separator
            continue;
        } else if (line.startsWith('|') && descIdx !== -1 && amtIdx !== -1 && !line.includes('|---')) {
            // If we already know the columns, and this is a markdown table row (even on a new page without header), parse it.
            inTable = true;
        } else if (!line.startsWith('|') && inTable) {
            inTable = false;
            continue;
        }

        if (inTable) {
            const cells = line.split('|').map(c => c.trim());
            if (descIdx !== -1 && amtIdx !== -1 && cells.length > Math.max(descIdx, amtIdx)) {
                const desc = cells[descIdx];
                // Remove non-numeric chars except dot/comma, then remove comma
                const amtStr = cells[amtIdx] ? cells[amtIdx].replace(/[^0-9.,]/g, '').replace(/,/g, '') : '';
                const qty = qtyIdx !== -1 && cells[qtyIdx] ? cells[qtyIdx].replace(/[^0-9.]/g, '') : '';
                const rate = rateIdx !== -1 && cells[rateIdx] ? cells[rateIdx].replace(/[^0-9.,]/g, '').replace(/,/g, '') : '';
                const dLower = (desc || '').toLowerCase();
                const isSummaryRow = dLower.includes('total') || dLower.includes('subtotal') || dLower.includes('amount') || dLower.includes('tax') || dLower.includes('cgst') || dLower.includes('sgst') || dLower.includes('igst') || dLower.includes('discount');
                if (desc && amtStr && !dLower.includes('description') && desc !== '-' && !isSummaryRow) {
                    let cleanDesc = desc.replace(/(?:serial|s\/\?n\b|sl\s*no)[\s\S]*$/gi, '').trim();
                    // if cleaning made it empty, use original
                    if (!cleanDesc) cleanDesc = desc;
                    lineItems.push({ description: cleanDesc, amount: amtStr, quantity: qty, unitPrice: rate });
                }
            }
        }
    }

    // 3a. Basic Amount (taxable amount - without GST)
    let basicAmount = '';
    // Try to find taxable/basic/sub-total amount (before tax)
    const basicPatterns = [
        // Ultimate root-cause regex: Look for Taxable Amount, then allow UP TO 50 characters of OCR noise (newlines, percentages, labels) and lock onto the very first currency value!
        /(?:TAXABLE|BASIC|ASSESSABLE)\s*(?:AMOUNT|VALUE|TOTAL)?[\s\S]{0,50}?([0-9]{1,3}(?:,[0-9]{2,3})*\.[0-9]{2})/i,
        /(?:SUB\s*TOTAL|NET\s*AMOUNT|BEFORE\s*TAX)[\s\S]{0,50}?([0-9]{1,3}(?:,[0-9]{2,3})*\.[0-9]{2})/i,
        // Fallback for markdown tables
        /\|\s*(?:TAXABLE|BASIC)\s*(?:AMOUNT|VALUE)?\s*\|\s*([0-9,]+\.[0-9]{2})\s*\|/i
    ];
    for (const pat of basicPatterns) {
        const m = markdown.match(pat);
        if (m) { basicAmount = m[1].replace(/,/g, '').trim(); break; }
    }
    // Reject if too small to be a real invoice amount
    if (basicAmount && parseFloat(basicAmount) < 10) basicAmount = '';

    // 3b. Gross Amount (total with tax) — prefer explicit labels, avoid GST% values
    if (!amount) {
        const grossPatterns = [
            // Explicit labels first (most reliable) with 50-char proximity matching
            /(?:GRAND\s*TOTAL|NET\s*PAYABLE|AMOUNT\s*PAYABLE|INVOICE\s*TOTAL|TOTAL\s*PAYABLE|AMOUNT\s*DUE)[\s\S]{0,50}?([0-9]{1,3}(?:,[0-9]{2,3})*\.[0-9]{2})/i,
            /(?:GROSS\s*AMOUNT|TOTAL\s*AMOUNT|FINAL\s*AMOUNT|INVOICE\s*VALUE)[\s\S]{0,50}?([0-9]{1,3}(?:,[0-9]{2,3})*\.[0-9]{2})/i,
            // Markdown table cell: |GROSS AMOUNT(IN INR) :|12344.00|
            /(?:GROSS|TOTAL|FINAL)\s*AMOUNT[^|]*\|?\s*:?\s*\|?\s*([0-9,]+\.?[0-9]*)/i,
        ];
        for (const pat of grossPatterns) {
            const m = markdown.match(pat);
            if (m) { amount = m[1].replace(/,/g, '').trim(); break; }
        }
    }
    // Reject if too small (e.g. "9" from GST %) or not a real amount
    if (amount && parseFloat(amount) < 100) amount = '';

    // Calculate sum of line items as a fallback for Basic Amount
    let lineItemsSum = 0;
    if (lineItems && lineItems.length > 0) {
        lineItemsSum = lineItems.reduce((sum, item) => sum + (parseFloat((item.amount || '').toString().replace(/,/g, '')) || 0), 0);
    }
    
    // If we couldn't find a basic amount via regex, fallback to line items sum, 
    // but ONLY if the sum makes logical sense (e.g. it cannot be greater than the Gross Amount).
    if (!basicAmount && lineItemsSum > 0) {
        let grossNum = parseFloat(amount); // Do NOT use Infinity, otherwise it bypasses the safety check!
        if (grossNum && lineItemsSum <= grossNum) {
            basicAmount = lineItemsSum.toFixed(2);
        }
    }

    try {
        const debugData = { vendorName, invoiceNumber, amount, basicAmount, date, poNumber, lineItemsSum };
        fs.writeFileSync(path.join(process.cwd(), 'debug_markdown.txt'), markdown);
        fs.writeFileSync(path.join(process.cwd(), 'debug_amounts.json'), JSON.stringify(debugData, null, 2));
    } catch (e) {
        console.error("Failed to write debug files", e);
    }

    return { vendorName, invoiceNumber, amount, basicAmount, date, poNumber, lineItems };
};

/**
 * Extracts data from a PDF file using OpenDataLoader
 * @param {string} inputPath - Path to the PDF file
 * @returns {Promise<Object>} Extracted invoice data
 */
export const extractPdfWithOpenDataLoader = async (inputPath) => {
    const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'odl-'));
    
    try {
        // Convert using opendataloader
        await convert(inputPath, {
            outputDir: tempDir,
            format: 'markdown'
        });

        // Find the generated markdown file
        const files = fs.readdirSync(tempDir);
        const mdFile = files.find(f => f.endsWith('.md'));
        
        if (!mdFile) {
            throw new Error('Failed to generate markdown from PDF');
        }

        const mdPath = path.join(tempDir, mdFile);
        const markdownContent = fs.readFileSync(mdPath, 'utf8');

        // Parse fields
        const fields = extractFieldsFromMarkdown(markdownContent);

        return {
            ...fields,
            rawText: markdownContent
        };
    } catch (error) {
        console.error('OpenDataLoader Extraction Error:', error);
        throw new Error(`PDF extraction failed: ${error.message}`);
    } finally {
        // Cleanup temp directory
        try {
            fs.rmSync(tempDir, { recursive: true, force: true });
        } catch (e) {
            console.warn('Failed to clean up OpenDataLoader temp directory:', e.message);
        }
    }
};
